extends RefCounted
const DISCOVERY=preload("res://tests/scenarios/test_p4_discovery.gd")
const TRACK: String="p4s:skill.search"
const NODE: String="p4s:node.attentive"
static func run(t: Sm2TestHarness) -> void:
	var s: Sm2JourneySession=DISCOVERY.make(); t.expect(s.new_game().ok,"hero screen world starts")
	var before: String=s.state_hash()
	var v: Dictionary=Sm2HeroDevelopmentView.build(s,TRACK)
	t.equal(v.selected.id,TRACK,"selected track preserved")
	t.equal(v.selected.earned,0,"own initial practice shown")
	t.equal(v.nodes.size(),1,"only selected direction's nodes")
	t.expect(not v.nodes[0].allowed,"authoritative initial purchase restriction")
	t.expect(str(v.nodes[0].effects[0]).contains("Ниша под кладкой"),"unlock effect described from content")
	t.equal(v.context.body_id,2,"context targets hero only")
	v.selected.earned=999; v.tracks[0].nodes.append("forged")
	t.equal(s.state_hash(),before,"read model detached from live body")
	v=Sm2HeroDevelopmentView.build(s,"p1:stat.strength")
	t.equal(v.nodes.size(),2,"existing strength chain displayed")
	t.equal(v.nodes[0].unlocks[0].id,"p1:node.strength_2","forward node connection")
	t.equal(v.nodes[1].requires[0].id,"p1:node.strength_1","backward node prerequisite")
	t.expect(not v.nodes[1].requires[0].owned,"prerequisite state visible")
	t.expect(not v.links.is_empty(),"existing characteristic contribution displayed")
	t.equal(Sm2HeroDevelopmentView.build(s,"invalid").selected.id,s._content.development.progression().track_ids()[0],"unknown UI selection falls back safely")
	t.equal(s.state_hash(),before,"navigation queries do not change state")
	s=DISCOVERY.prepared(t,Sm2SaveStore.new("user://hero-screen-tests"))
	v=Sm2HeroDevelopmentView.build(s,TRACK)
	t.expect(v.nodes[0].allowed,"available node agrees with command")
	t.equal(v.selected.available,100,"available experience shown")
	t.expect(s.act(s.command("buy_node",2,NODE)).ok,"common purchase")
	v=Sm2HeroDevelopmentView.build(s,TRACK)
	t.expect(v.nodes[0].owned and not v.nodes[0].allowed,"purchased node marked and disabled")
	t.equal(v.selected.level,2,"own level retained")
	t.equal(v.selected.spent,100,"spent amount shown")
	t.equal(v.selected.available,0,"remainder shown")
	t.expect(s.save_game().ok,"screen uses existing save contract")
	t.expect(s.act(s.command("start_battle")).ok,"battle starts for read-only boundary")
	before=s.state_hash(); v=Sm2HeroDevelopmentView.build(s,TRACK)
	t.expect(v.nodes.is_empty() and v.selected.is_empty() and not v.message.is_empty(),"battle shows no stale pre-battle practice")
	t.equal(s.state_hash(),before,"busy query does not advance battle")
	t.expect(s.load_game().ok,"existing camp reloaded")
	t.expect(s.act(s.command("end_life")).ok,"hero dies")
	v=Sm2HeroDevelopmentView.build(s,TRACK)
	t.expect(v.nodes.is_empty() and v.tracks.is_empty() and v.hero_id==0,"no body has no invented progress")
	t.expect(s.act(s.command("incarnate",8)).ok,"new incarnation")
	v=Sm2HeroDevelopmentView.build(s,TRACK)
	t.equal(v.context.body_id,8,"new read model targets new body")
	t.equal(v.selected.earned,0,"new body shows zero practice")
	t.expect(not v.nodes[0].owned and not v.nodes[0].allowed,"new body does not inherit learned node")
	t.complete_suite("p4_hero_screen")
