extends "res://tests/display_ui.gd"
func _run() -> void:
	OS.add_logger(captured)
	var args: PackedStringArray=OS.get_cmdline_user_args()
	if args.size()==2 and args[0]=="--output": output=args[1]
	DirAccess.make_dir_recursive_absolute(output); display_report={"captures":[]}
	await set_resolution(Vector2i(2560,1440))
	app=(load("res://scenes/main.tscn") as PackedScene).instantiate() as Control; root.add_child(app); await _frames()
	await _press("NewSurvivalTissuesButton"); life=app.find_child("LifeScreen",true,false) as Sm2LifeScreen
	var s: Sm2JourneySession=life.session as Sm2JourneySession; var before: String=s.state_hash()
	t.expect(app.find_child("CampHome",true,false)!=null,"new campaign opens the camp hub")
	var scene: Sm2CampScene=app.find_child("CampScene",true,false) as Sm2CampScene
	t.expect(scene!=null and scene.background!=null and scene.figure!=null and scene.fire!=null,"environment hero and fire are separate scene layers")
	t.expect(not scene.model.objects.is_empty(),"stationary stash is projected from real ground items")
	t.expect(_button("CampRest").disabled and _button("CampCraft").disabled,"unimplemented activities cannot fake rewards or time")
	var facts: Dictionary=Sm2CampSceneView.build(s); facts.hero.combat.items.clear()
	t.expect(not Sm2CampSceneView.build(s).hero.combat.items.is_empty(),"visual facts are detached from inventory")
	t.equal(s.state_hash(),before,"building and editing detached scene cannot change the world")
	await _capture("camp-2560.png")
	await _press("CampInventory"); await _press("WorkspaceEquipment_weapon"); await _press("WorkspaceDrop"); await _press("WorkspaceBack")
	scene=app.find_child("CampScene",true,false) as Sm2CampScene
	t.expect("sword" not in scene.art.layers(scene.model.hero),"dropping equipped sword updates the separate hero layers")
	t.expect(s.act(s.command("wear_item",2,"20")).ok,"restore actual sword through normal inventory command")
	life.redraw(); await _frames()
	scene=app.find_child("CampScene",true,false) as Sm2CampScene
	t.expect("sword" in scene.art.layers(scene.model.hero),"wearing sword restores visible equipment")
	before=s.state_hash()
	await _press("CampMap"); await _key(KEY_ESCAPE)
	t.expect(app.find_child("CampHome",true,false)!=null,"Escape returns from map to camp")
	t.equal(s.state_hash(),before,"return navigation is read only")
	await _press("MapLocation_enclave")
	t.equal(life._map_selection,"enclave","map selects destination for inspection")
	t.equal(s.state_hash(),before,"map selection cannot travel or change time")
	t.equal(s.journey().region.location_id,"camp","activities still belong to actual camp")
	t.expect(_button("PsiTrain")!=null,"camp retains actual practice")
	t.expect(_button("UpgradeCollect_psi_amplifier")==null,"previewing enclave cannot expose remote procedures")
	await _press("PsiTrain")
	t.equal(s.journey().region.seconds,10,"one real practice advances ten seconds")
	var old: Button=_button("Travel_ruins")
	t.expect(s.act(s.command("practice",2,"p5:activity.psionics")).ok,"external action advances revision without repaint")
	before=s.state_hash(); old.pressed.emit(); await _frames()
	t.equal(s.state_hash(),before,"captured old travel refuses changed revision")
	t.equal(s.journey().region.seconds,20,"rejected old travel adds no time")
	await _press("Travel_ruins")
	t.equal(s.journey().region.seconds,1820,"travel uses authored thirty minutes exactly")
	t.equal(s.journey().region.bodies["4"],"ruins","living companion travels with hero")
	t.expect(_button("PsiTrain")==null,"remote camp exercise absent in ruins")
	await _press("CampHomeBack")
	scene=app.find_child("CampScene",true,false) as Sm2CampScene
	t.equal(scene.model.location,"ruins","background follows actual travel")
	t.expect(scene.background.texture is AtlasTexture,"ruins uses its own environmental image")
	t.expect(scene.model.objects.is_empty(),"stationary stash does not travel with the hero")
	await _capture("ruins-2560.png")
	await _press("Explore_first_aid")
	t.expect(s.journey().exploration.collected.has("first_aid"),"real local exploration completes")
	t.expect((app.find_child("CampNotice",true,false) as Label).text.contains("земли"),"search explains physical ground loot")
	await _press("CampInventory"); t.expect(app.find_child("SurvivalWorkspace",true,false)!=null,"inventory shortcut opens existing workspace")
	await _press("WorkspaceBack"); await _press("Travel_enclave")
	t.expect(_button("UpgradeCollect_psi_amplifier")!=null,"enclave exposes local kit")
	await _press("UpgradeCollect_psi_amplifier"); await _press("UpgradeApply_psi_amplifier")
	t.expect("p5:upgrade.psi_amplifier" in s.world.bodies[2].upgrades.installed,"local procedure consumes kit and installs actual upgrade")
	await _press("CampHomeBack")
	scene=app.find_child("CampScene",true,false) as Sm2CampScene
	t.expect("p5:upgrade.psi_amplifier" in scene.model.hero.upgrades,"body improvements are available to visual variants")
	await _capture("enclave-2560.png")
	await _press("WorldSave"); before=s.state_hash(); await _press("WorldLoad")
	t.equal(s.state_hash(),before,"map, clock, visits and procedures persist exactly")
	for dimensions: Vector2i in [Vector2i(1920,1080),Vector2i(1280,720),Vector2i(1280,800)]:
		await set_resolution(dimensions); await _press("MapLocation_camp")
		t.equal(life._map_selection,"camp","scaled map click selects correct place")
		await _press("CampHomeBack")
		await _capture("camp-%s-%s.png" % [dimensions.x,dimensions.y])
	t.equal(s.state_hash(),before,"scaled map inspection does not mutate world")
	await _press("Travel_camp")
	t.expect(_button("WorldEndLife").disabled,"end life preserves first-encounter prerequisite")
	await _press("CampHomeBack")
	await _press("WorldSave"); before=s.state_hash(); await _press("WorldLoad")
	t.equal(s.state_hash(),before,"return to camp saves full journey")
	_finish()
