extends "res://tests/display_ui.gd"
func _run() -> void:
	OS.add_logger(captured)
	var args: PackedStringArray=OS.get_cmdline_user_args()
	if args.size()==2 and args[0]=="--output": output=args[1]
	DirAccess.make_dir_recursive_absolute(output); display_report={"captures":[]}
	await set_resolution(Vector2i(2560,1440))
	app=(load("res://scenes/main.tscn") as PackedScene).instantiate() as Control; root.add_child(app); await _frames()
	await _capture("start-2560.png")
	t.expect(_button("ContinueSurvivalTissuesButton")==null and _button("NewSurvivalTissuesButton")!=null,"fresh menu offers new incarnation instead of continue")
	await _press("CampaignsButton"); await _press("CampaignSelect_1")
	t.equal(app._campaigns().selected(),1,"real chooser persists selection")
	await _capture("empty-campaigns.png")
	await _key(KEY_ESCAPE)
	t.expect(app.find_child("CampaignChooser",true,false)==null,"Escape closes chooser without loading")
	await _press("NewSurvivalTissuesButton")
	life=app.find_child("LifeScreen",true,false) as Sm2LifeScreen
	var second: Sm2JourneySession=life.session as Sm2JourneySession
	t.equal((second._store as Sm2CampaignStore).campaign_index,1,"new game uses selected empty campaign")
	await _press("WorldSave"); var old_hash: String=second.state_hash()
	var path: String=second._store._slot_path(second.slot_name()); var bytes: PackedByteArray=FileAccess.get_file_as_bytes(path)
	await _press("PsiTrain"); await _press("WorldSave")
	var saved_hash: String=second.state_hash()
	await _press("PsiTrain"); var unsaved: String=second.state_hash()
	await _press("WorldMenu"); await _press("ResumeMainButton")
	t.equal(second.state_hash(),unsaved,"resume retains unsaved progress in second campaign")
	await _press("WorldMenu"); await _press("CampaignsButton")
	await _press("CampaignOpen_0"); life=app.find_child("LifeScreen",true,false) as Sm2LifeScreen
	var first: Sm2JourneySession=life.session as Sm2JourneySession
	await _press("WorldSave"); var first_path: String=first._store._slot_path(first.slot_name()); var first_bytes: PackedByteArray=FileAccess.get_file_as_bytes(first_path)
	await _press("WorldMenu"); await _press("CampaignsButton"); await _press("CampaignOpen_2")
	life=app.find_child("LifeScreen",true,false) as Sm2LifeScreen; var third: Sm2JourneySession=life.session as Sm2JourneySession
	await _press("Travel_ruins"); await _press("WorldSave")
	var third_path: String=third._store._slot_path(third.slot_name()); var third_bytes: PackedByteArray=FileAccess.get_file_as_bytes(third_path)
	await _press("WorldMenu"); await _press("CampaignsButton")
	t.expect(app.find_child("CampaignChooser",true,false)!=null,"all three occupied worlds remain selectable")
	t.expect(app._campaigns().open(0,false).ok==false,"new game cannot replace an occupied slot")
	for dimensions: Vector2i in [Vector2i(2560,1440),Vector2i(1920,1080),Vector2i(1280,720),Vector2i(1280,800)]:
		await set_resolution(dimensions)
		await _capture("campaigns-%s-%s.png" % [dimensions.x,dimensions.y])
		await _press("CampaignSelect_1")
	t.equal(third.state_hash(),(app._life as Sm2JourneySession).state_hash(),"choosing a slot cannot replace live campaign")
	await _press("CampaignOpen_1"); life=app.find_child("LifeScreen",true,false) as Sm2LifeScreen
	second=life.session as Sm2JourneySession; t.equal(second.state_hash(),saved_hash,"explicit slot load restores saved practice")
	await _press("WorldMenu")
	var file: FileAccess=FileAccess.open(path,FileAccess.WRITE); file.store_string("{broken"); file.close()
	await _press("CampaignsButton")
	t.expect((app.find_child("CampaignInfo_1",true,false) as Label).text.contains("Резервная копия"),"chooser explains backup recovery")
	await set_resolution(Vector2i(2560,1440)); await _capture("backup-choice.png")
	await _press("CampaignOpen_1"); life=app.find_child("LifeScreen",true,false) as Sm2LifeScreen; second=life.session as Sm2JourneySession
	t.equal(second.state_hash(),old_hash,"backup recovers older checkpoint exactly")
	t.expect((app.find_child("CampNotice",true,false) as Label).text.contains("резервная копия"),"recovery visible in camp")
	await _press("WorldSave")
	t.equal(FileAccess.get_file_as_bytes(path+".bak"),bytes,"saving recovery preserves backup")
	t.equal(FileAccess.get_file_as_bytes(first_path),first_bytes,"recovery leaves first campaign intact")
	t.equal(FileAccess.get_file_as_bytes(third_path),third_bytes,"recovery leaves third campaign intact")
	await _press("Travel_ruins"); await _press("WorldBattle")
	screen=app.find_child("BattleScreen",true,false) as Sm2BattleScreen; screen.auto_advance=false
	await _press("SaveBattleButton"); var battle_hash: String=second.state_hash()
	await _cell(Vector2i(2,1),false); await _press("SaveBattleButton")
	file=FileAccess.open(path,FileAccess.WRITE); file.store_string("{broken battle"); file.close()
	await _press("LoadBattleButton")
	t.equal(second.state_hash(),battle_hash,"battle backup restores exact turn state")
	t.expect(screen._notice.text.contains("резервной копии"),"battle recovery notice visible")
	await _press("BattleMenuButton"); await _press("WorldMenu"); await _press("CampaignsButton")
	await _press("CampaignDelete_1"); await _capture("delete-confirm.png"); await _press("CampaignCancelDelete")
	t.expect(FileAccess.file_exists(path),"cancel deletion keeps selected file")
	await _press("CampaignDelete_1"); await _press("CampaignConfirmDelete")
	t.expect(app._campaigns().occupied(1),"first confirmation does not delete anything")
	t.equal(app._campaign_delete_step,2,"first confirmation opens distinct second step")
	t.expect(_button("CampaignOpen_0").disabled,"final confirmation blocks underlying slot actions")
	await _capture("delete-final-confirm.png"); await _key(KEY_ESCAPE)
	t.expect(app._campaigns().occupied(1),"Escape at second step cancels deletion")
	# A replacement between confirmations must survive the stale final button.
	await _press("CampaignDelete_1"); await _press("CampaignConfirmDelete")
	var replaced: FileAccess=FileAccess.open(path+".tmp",FileAccess.WRITE); replaced.store_string("changed during confirmation"); replaced.close()
	var retained: PackedByteArray=FileAccess.get_file_as_bytes(path)
	await _press("CampaignFinalDelete")
	t.equal(FileAccess.get_file_as_bytes(path),retained,"changed slot survives second confirmation")
	t.expect(FileAccess.file_exists(path+".tmp"),"stale deletion does not remove replacement file")
	await _press("CampaignDelete_1"); await _press("CampaignConfirmDelete"); await _press("CampaignFinalDelete")
	t.expect(not app._campaigns().occupied(1),"confirmed deletion clears selected primary and backup")
	t.expect(app._life==null,"deleting live campaign closes only that session")
	t.equal(FileAccess.get_file_as_bytes(first_path),first_bytes,"delete preserves first campaign")
	t.equal(FileAccess.get_file_as_bytes(third_path),third_bytes,"delete preserves third campaign")
	await _press("CampaignClose")
	root.remove_child(app); app.queue_free(); await _frames()
	app=(load("res://scenes/main.tscn") as PackedScene).instantiate() as Control; root.add_child(app); await _frames()
	t.equal(app._campaigns().selected(),1,"selected campaign survives restart")
	await _press("CampaignsButton"); await _press("CampaignOpen_2")
	life=app.find_child("LifeScreen",true,false) as Sm2LifeScreen
	t.equal(life.session.state_hash(),third.state_hash(),"restart loads correct surviving world")
	await _press("WorldMenu"); await _press("CampaignsButton")
	for index: int in [0,2]:
		await _press("CampaignDelete_"+str(index))
		app._confirm_campaign_delete(index,app._campaign_token)
		t.expect(app._campaigns().occupied(index),"final handler cannot bypass first confirmation")
		await _press("CampaignConfirmDelete"); await _press("CampaignFinalDelete")
	await _press("CampaignClose")
	t.expect(_button("ContinueSurvivalTissuesButton")==null,"removing last save removes Continue")
	t.equal(_button("NewSurvivalTissuesButton").text,"Новое воплощение","last deletion restores new incarnation")
	_finish()
