extends "res://tests/display_ui.gd"

func _run() -> void:
	OS.add_logger(captured)
	var args: PackedStringArray=OS.get_cmdline_user_args()
	if args.size()==2 and args[0]=="--output": output=args[1]
	DirAccess.make_dir_recursive_absolute(output); display_report={"captures":[]}
	var watchdog: Timer=Timer.new(); watchdog.wait_time=90; watchdog.one_shot=true; watchdog.timeout.connect(func() -> void: t.expect(false,"controls scenario timeout"); _finish()); root.add_child(watchdog); watchdog.start()
	await set_resolution(Vector2i(2560,1440))
	var prefs: Sm2ControlPreferences=Sm2ControlPreferences.new()
	t.expect(prefs.read().ok and not FileAccess.file_exists(prefs.path),"missing controls defaults without writing")
	var invalid: Dictionary=Sm2ControlPreferences.DEFAULT.duplicate(); invalid.slot_1=KEY_ESCAPE
	t.expect(not prefs.write(invalid),"reserved escape rejected")
	invalid=Sm2ControlPreferences.DEFAULT.duplicate(); invalid.slot_1=KEY_2
	t.expect(not prefs.write(invalid),"duplicate shortcut rejected")
	invalid=Sm2ControlPreferences.DEFAULT.duplicate(); invalid.erase("wait")
	t.expect(not prefs.write(invalid),"incomplete settings rejected")
	invalid=Sm2ControlPreferences.DEFAULT.duplicate(); invalid.wait="W"
	t.expect(not prefs.write(invalid),"wrong type rejected")
	app=(load("res://scenes/main.tscn") as PackedScene).instantiate() as Control; root.add_child(app); await _frames()
	await _key(KEY_F10)
	var settings: Sm2SettingsScreen=app.find_child("SettingsScreen",true,false) as Sm2SettingsScreen
	t.expect(settings!=null,"F10 opens settings from menu")
	var editor: Sm2ControlsEditor=settings.bindings_editor
	t.equal(editor.rows.size(),Sm2ControlPreferences.DEFAULT.size(),"all bindings have presentation labels")
	await _press("Bind_slot_4"); await _key(KEY_5)
	t.equal(editor.capturing,"slot_4","conflict continues capture")
	t.expect(editor.message.text.contains("занята"),"conflict explained visibly")
	t.equal(editor.draft.slot_4,KEY_4,"conflict preserves old value")
	await _key(KEY_ESCAPE)
	t.equal(app._page,"settings","escape cancels capture instead of exiting settings")
	t.equal(editor.capturing,"","capture cancelled")
	await _press("Bind_slot_4"); await _key(KEY_TAB)
	t.equal(editor.draft.slot_4,KEY_4,"reserved focus navigation cannot be assigned")
	await _key(KEY_P)
	t.equal(editor.draft.slot_4,KEY_P,"new physical key captured")
	t.equal(Sm2Controls.bindings.slot_4,KEY_4,"draft does not change live controls")
	t.expect(not FileAccess.file_exists(prefs.path),"draft does not save")
	await _press("BindingsDiscard"); t.equal(editor.draft.slot_4,KEY_4,"discard restores live values")
	await _press("Bind_slot_4"); await _key(KEY_P); await _press("BindingsSave")
	t.equal(prefs.read().value.slot_4,KEY_P,"confirmed key written")
	await _press("Bind_inventory"); await _key(KEY_U); await _press("BindingsSave")
	await _press("Bind_end_turn"); await _key(KEY_R); await _press("BindingsSave")
	await _press("BindingsDefaults")
	t.equal(editor.draft.slot_4,KEY_4,"defaults prepare draft")
	t.equal(Sm2Controls.bindings.slot_4,KEY_P,"defaults require saving")
	await _press("BindingsDiscard")
	var bad_store: Sm2ControlPreferences=Sm2ControlPreferences.new(); bad_store.path="user://missing-dir/controls.cfg"; editor.preferences=bad_store
	await _press("Bind_slot_4"); await _key(KEY_O); await _press("BindingsSave")
	t.equal(Sm2Controls.bindings.slot_4,KEY_P,"failed write keeps live binding")
	t.equal(prefs.read().value.slot_4,KEY_P,"failed write preserves original file")
	t.expect(editor.message.text.contains("Не удалось"),"write failure explained")
	editor.preferences=prefs
	await _press("SettingsBack"); await _key(KEY_F10)
	settings=app.find_child("SettingsScreen",true,false) as Sm2SettingsScreen; editor=settings.bindings_editor
	t.equal(editor.draft.slot_4,KEY_P,"leaving discards failed or unsaved edit")
	for dimensions: Vector2i in [Vector2i(2560,1440),Vector2i(1280,720)]:
		await set_resolution(dimensions)
		t.expect(settings.get_global_rect().encloses(_button("BindingsSave").get_global_rect()),"save stays visible "+str(dimensions))
		await _capture("controls-%s.png" % dimensions.x)
	await _press("SettingsBack"); await _press("NewSurvivalTissuesButton")
	life=app.find_child("LifeScreen",true,false) as Sm2LifeScreen
	var session: Sm2JourneySession=life.session as Sm2JourneySession
	var before: String=session.state_hash()
	t.expect(_button("CampInventory").text.contains("[U]"),"camp caption uses new binding")
	await _key(KEY_I); t.expect(app.find_child("SurvivalWorkspace",true,false)==null,"old inventory key no longer opens screen")
	await _key(KEY_U); t.expect(app.find_child("SurvivalWorkspace",true,false)!=null,"new inventory key opens actual screen")
	await _key(KEY_J); t.expect(app.find_child("JournalScreen",true,false)==null,"camp shortcuts blocked under workspace")
	var search: LineEdit=app.find_child("WorkspaceSearch",true,false) as LineEdit
	search.grab_focus()
	var typed: InputEventKey=InputEventKey.new(); typed.physical_keycode=KEY_E; typed.unicode=101; typed.pressed=true; root.push_input(typed); await _frames()
	t.expect(search.text.contains("e"),"search accepts key as text")
	t.equal(session.state_hash(),before,"typing and inspecting never change campaign")
	search.release_focus(); await _key(KEY_ESCAPE)
	await _key(KEY_J); t.expect(app.find_child("JournalScreen",true,false)!=null,"journal shortcut opens journal")
	await _key(KEY_ESCAPE); await _key(KEY_H); t.expect(app.find_child("SoulScreen",true,false)!=null,"soul shortcut opens soul")
	await _key(KEY_ESCAPE); await _key(KEY_C); t.expect(app.find_child("HeroDevelopmentScreen",true,false)!=null,"development shortcut opens development")
	await _key(KEY_ESCAPE); await _key(KEY_B); t.expect(app.find_child("SurvivalWorkspace",true,false)!=null,"body shortcut opens body")
	await _key(KEY_ESCAPE)
	t.equal(session.state_hash(),before,"navigation preserves world hash")
	# Persist a real campaign, then create a fresh Main to exercise startup loading.
	await _press("WorldSave")
	root.remove_child(app); app.queue_free(); await _frames(); Sm2Controls.bindings=Sm2ControlPreferences.DEFAULT.duplicate()
	app=(load("res://scenes/main.tscn") as PackedScene).instantiate() as Control; root.add_child(app); await _frames()
	t.equal(Sm2Controls.bindings.slot_4,KEY_P,"new Main restores custom key from disk")
	await _press("ContinueSurvivalTissuesButton"); t.equal(app._life.state_hash(),before,"campaign load independent of controls")
	SHIELD.learn(app._life as Sm2JourneySession,t); life=app.find_child("LifeScreen",true,false) as Sm2LifeScreen; life.redraw(); await _frames()
	await _press("Travel_ruins"); await _press("WorldBattle")
	screen=app.find_child("BattleScreen",true,false) as Sm2BattleScreen; screen.auto_advance=false
	t.expect(_button("Ability_impulse").text.begins_with("P ·"),"battle caption updated")
	t.expect(_button("Ability_impulse").tooltip_text.contains("Клавиша: P"),"battle tooltip updated")
	await _key(KEY_4); t.equal(screen._selected,"","old battle key does not select")
	await _key(KEY_P); t.equal(screen._selected,"p5:ability.impulse","new battle key selects real impulse")
	await _press("MoveButton")
	# Physical position remains P when the logical layout produces a Cyrillic character.
	typed=InputEventKey.new(); typed.physical_keycode=KEY_P; typed.keycode=1087; typed.pressed=true; root.push_input(typed); await _frames()
	t.equal(screen._selected,"p5:ability.impulse","physical key is independent of logical layout")
	await _press("MoveButton")
	typed=InputEventKey.new(); typed.physical_keycode=KEY_P; typed.pressed=true; typed.echo=true; root.push_input(typed); await _frames()
	t.equal(screen._selected,"","echo cannot select or execute")
	typed.echo=false; typed.ctrl_pressed=true; root.push_input(typed); await _frames()
	t.equal(screen._selected,"","modified shortcut ignored")
	await _press("DevelopmentButton"); before=app._life.state_hash()
	await _key(KEY_P); await _key(KEY_R); await _key(KEY_W)
	t.equal(app._life.state_hash(),before,"development overlay blocks action and turn keys")
	await _press("CloseDevelopmentButton")
	var revision: int=int(screen.state.revision)
	await _key(KEY_W)
	t.equal(int(screen.state.revision),revision+1,"wait key executes one real command")
	revision=int(screen.state.revision)
	await _key(KEY_E); t.equal(int(screen.state.revision),revision,"old end-turn key no longer executes")
	await _key(KEY_R)
	t.equal(int(screen.state.revision),revision+1,"end-turn key executes one real command")
	before=app._life.state_hash(); await _key(KEY_R)
	t.equal(app._life.state_hash(),before,"enemy turn blocks player hotkey")
	await set_resolution(Vector2i(2560,1440)); await _capture("battle-controls.png")
	# Invalid disk data returns the complete safe default map, never partial bindings.
	var file: ConfigFile=ConfigFile.new(); file.set_value("controls","version",99); file.save(prefs.path)
	Sm2Controls.initialize(); t.expect(not Sm2Controls.load_ok,"unknown format reported")
	t.equal(Sm2Controls.bindings,Sm2ControlPreferences.DEFAULT,"bad disk file restores all defaults")
	t.expect(prefs.write(Sm2ControlPreferences.DEFAULT),"default map can be explicitly saved")
	_finish()
