extends "res://tests/p4_prosthesis_ui.gd"
const DISCOVERY_TEST=preload("res://tests/scenarios/test_p4_discovery.gd")
func _run() -> void:
	OS.add_logger(captured)
	var args: PackedStringArray=OS.get_cmdline_user_args()
	if args.size()==2 and args[0]=="--output": output=args[1]
	DirAccess.make_dir_recursive_absolute(output)
	root.content_scale_size=Vector2i.ZERO; root.size=Vector2i(1000,700)
	app=(load("res://scenes/main.tscn") as PackedScene).instantiate() as Control; root.add_child(app); await _frames()
	await _capture("menu.png")
	await _press("NewDiscoveryButton"); life=app.find_child("LifeScreen",true,false) as Sm2LifeScreen
	t.expect(life!=null,"new discovery mode opens")
	if life==null: _finish(); return
	var s: Sm2JourneySession=life.session as Sm2JourneySession
	t.equal(s.format_id(),Sm2JourneySession.DISCOVERY_FORMAT,"explicit discovery profile")
	t.expect(_button("DiscoveryLearn_attentive").disabled,"node unavailable initially")
	t.expect(_button("Explore_hidden_niche").disabled,"hidden site inaccessible initially")
	t.expect((app.find_child("ExploreStatus_hidden_niche",true,false) as Label).text.contains("Внимательный осмотр"),"site explains required node")
	await _press("Explore_first_aid")
	t.equal(s.world.bodies[2].progress.tracks[DISCOVERY_TEST.TRACK].earned,50,"ordinary search still trains hero")
	await _press("WorldSave"); var saved: String=s.state_hash()
	await _press("WorldMenu"); await _press("ContinueDiscoveryButton")
	life=app.find_child("LifeScreen",true,false) as Sm2LifeScreen
	t.equal(life.session.state_hash(),saved,"separate menu continuation")
	# Real battle in a deterministic fixture keeps the hero alive for the unlock flow.
	s=Sm2JourneySession.new(DISCOVERY_TEST.fixture_content(),Sm2AiContentLoader.load_profile().profile,Sm2SaveStore.new("user://discovery-ui-flow"))
	t.expect(s.new_game().ok,"discovery UI fixture starts")
	app.set("_life",s); app.set("_page","life"); app.call("_redraw_page"); await _frames()
	life=app.find_child("LifeScreen",true,false) as Sm2LifeScreen
	await _press("Explore_first_aid"); await _fight_to_retreat(s)
	t.expect(_button("DiscoveryLearn_attentive").disabled,"after battle 50 own XP is insufficient")
	await _press("Explore_workshop")
	t.expect(not _button("DiscoveryLearn_attentive").disabled,"100 own XP enables purchase")
	t.expect(_button("Explore_hidden_niche").disabled,"level 2 does not replace learned node")
	root.size=Vector2i(1280,1000); await _frames(); await _capture("can-learn.png")
	var companion: Dictionary=s.world.bodies[4].to_data()
	await _press("DiscoveryLearn_attentive")
	t.equal(s.world.bodies[2].progress.tracks[DISCOVERY_TEST.TRACK].earned,100,"purchase preserves earned XP")
	t.equal(s.world.bodies[2].progress.tracks[DISCOVERY_TEST.TRACK].spent,100,"purchase spends correct track")
	t.equal(s.world.bodies[4].to_data(),companion,"purchase leaves companion intact")
	t.expect((app.find_child("SearchProgress_search",true,false) as Label).text.contains("уровень 2"),"level stays 2 in UI")
	t.expect((app.find_child("DiscoveryBalance_attentive",true,false) as Label).text.contains("доступно 0"),"remaining XP shown separately")
	t.expect(_button("DiscoveryLearn_attentive").disabled,"owned node cannot be charged twice")
	t.expect(not _button("Explore_hidden_niche").disabled,"learned node enables actual site button")
	await _capture("learned.png")
	await _press("WorldSave"); saved=s.state_hash(); await _press("WorldLoad")
	t.equal(s.state_hash(),saved,"load retains learned node without duplicate charge")
	t.expect(not _button("Explore_hidden_niche").disabled,"load retains node access")
	await _press("Explore_hidden_niche")
	t.equal(s.journey().care.supplies.medicine,6,"hidden supplies awarded through mouse action")
	t.equal(s.journey().care.supplies.parts,6,"hidden parts awarded through mouse action")
	t.equal(s.world.bodies[2].progress.tracks[DISCOVERY_TEST.TRACK].earned,150,"hidden search gives practice")
	t.expect(_button("Explore_hidden_niche").disabled,"hidden place cannot be collected twice")
	await _press("WorldSave"); saved=s.state_hash(); await _press("WorldLoad")
	t.equal(s.state_hash(),saved,"collected hidden site and spent XP restored")
	await _press("WorldEndLife"); await _press("WorldConfirmDeath"); await _press("WorldIncarnate8")
	t.expect(s.world.bodies[8].progress.tracks[DISCOVERY_TEST.TRACK].nodes.is_empty(),"new body does not inherit unlock")
	t.expect(_button("DiscoveryLearn_attentive").disabled,"new body must earn practice first")
	t.expect(_button("Explore_hidden_niche").disabled,"new body cannot replenish collected hidden site")
	t.equal((app.find_child("ExploreStatus_hidden_niche",true,false) as Label).text,"Собрано","world collected marker survives node loss")
	await _press("WorldSave"); await _capture("new-life.png")
	_finish()
