extends "res://tests/display_ui.gd"
const RESULTS: GDScript=preload("res://tests/scenarios/test_battle_results.gd")
const TISSUES: GDScript=preload("res://tests/scenarios/test_survival_tissues.gd")
func _run() -> void:
	OS.add_logger(captured)
	var args: PackedStringArray=OS.get_cmdline_user_args()
	if args.size()==2 and args[0]=="--output": output=args[1]
	DirAccess.make_dir_recursive_absolute(output); display_report={"captures":[]}
	await set_resolution(Vector2i(2560,1440))
	app=(load("res://scenes/main.tscn") as PackedScene).instantiate() as Control; root.add_child(app); await _frames()
	await _press("NewSurvivalTissuesButton"); life=app.find_child("LifeScreen",true,false) as Sm2LifeScreen
	var session: Sm2JourneySession=life.session as Sm2JourneySession
	var before: String=session.state_hash(); await _press("CampSoul")
	var soul: Sm2SoulScreen=app.find_child("SoulScreen",true,false) as Sm2SoulScreen
	t.equal(soul.model.history.size(),1,"one actual initial incarnation")
	t.equal(soul.model.knowledge,session.view().knowledge,"actual Soul knowledge names")
	t.expect(_button("SoulIncarnate18").disabled,"living hero cannot incarnate")
	t.equal(session.state_hash(),before,"opening Soul is read only")
	soul.model.history[0].name="changed"; t.equal(session.state_hash(),before,"detached model cannot edit world")
	await _key(KEY_ESCAPE); t.expect(app.find_child("SoulScreen",true,false)==null,"Escape returns to camp")
	t.equal(session.state_hash(),before,"closing screen is read only")
	var fixture: Sm2JourneySession=RESULTS.started(t,true)
	app._life=fixture; app._page="life"; app._redraw_page(); await _frames()
	await _press("CampSoul"); soul=app.find_child("SoulScreen",true,false) as Sm2SoulScreen
	t.expect(soul.model.busy and soul.model.carriers.is_empty(),"battle has no stale body candidates")
	RESULTS.finish(t,fixture,true); TISSUES.bandage_all(t,fixture)
	t.expect(fixture.act(fixture.command("travel",0,"camp")).ok,"survivors return after actual battle")
	t.expect(fixture.act(fixture.command("end_life")).ok,"actual first life ends")
	soul.refresh(); await _frames()
	t.equal(soul.model.hero,0,"Soul has no body")
	t.equal(soul.model.available,1,"only prepared local body allowed")
	t.expect(_button("SoulIncarnate2").disabled,"former body cannot be reused")
	t.expect(_button("SoulIncarnate8")==null,"remote corpse not offered")
	t.expect(not _button("SoulIncarnate18").disabled,"prepared local corpse offered")
	before=fixture.state_hash(); var items: Dictionary=fixture.journey().survival.inventory.to_data()
	var companion: Dictionary=fixture.world.bodies[4].progress.to_data(); var knowledge: Array=fixture.world.soul.knowledge.duplicate()
	for dimensions: Vector2i in [Vector2i(2560,1440),Vector2i(1920,1080),Vector2i(1280,720),Vector2i(1280,800)]:
		await set_resolution(dimensions); await _capture("soul-%s-%s.png" % [dimensions.x,dimensions.y])
	t.equal(fixture.state_hash(),before,"resizing Soul does not change world")
	await _press("SoulSave")
	var old: Button=_button("SoulIncarnate18")
	t.expect(fixture.act(fixture.command("incarnate",18)).ok,"external incarnation changes displayed context")
	var changed: String=fixture.state_hash(); old.pressed.emit(); await _frames()
	t.equal(fixture.state_hash(),changed,"stale incarnation button cannot execute again")
	t.expect((soul.find_child("SoulNotice",true,false) as Label).text.contains("Устаревшая"),"stale command explained")
	await _press("SoulLoad"); t.equal(fixture.state_hash(),before,"load restores unembodied Soul exactly")
	await _press("SoulIncarnate18")
	t.equal(fixture.world.hero_id(),18,"real UI incarnation selects exact body")
	t.equal(soul.model.history.size(),2,"new incarnation appears in actual history")
	t.expect(soul.model.history[0].ended and not soul.model.history[1].ended,"history separates ended and current life")
	t.equal(fixture.world.soul.knowledge,knowledge,"Soul retains knowledge")
	t.equal(fixture.world.bodies[4].progress.to_data(),companion,"companion keeps separate growth")
	# JSON loading normalizes numeric variants; compare exact canonical item facts.
	t.equal(Sm2Canonical.stringify(fixture.journey().survival.inventory.to_data()),Sm2Canonical.stringify(items),"incarnation never transfers or duplicates inventory")
	for track: Sm2ProgressTrackState in fixture.world.bodies[18].progress.tracks.values(): t.equal(track.earned,0,"new body's own practice starts fresh")
	await set_resolution(Vector2i(2560,1440)); await _capture("soul-incarnated.png")
	t.expect(fixture.act(fixture.command("end_life")).ok,"second body can end through existing command")
	soul.refresh(); await _frames(); t.equal(soul.model.available,0,"finite local carriers can be exhausted")
	await _capture("soul-exhausted.png")
	await _press("SoulLoad"); await _press("SoulIncarnate18"); await _press("SoulSave")
	before=fixture.state_hash(); await _press("SoulLoad"); t.equal(fixture.state_hash(),before,"incarnated campaign roundtrip exact")
	await _press("SoulBack"); t.expect(app.find_child("SoulScreen",true,false)==null,"return button closes Soul")
	await _press("CampSoul"); soul=app.find_child("SoulScreen",true,false) as Sm2SoulScreen
	t.equal(soul.model.history.size(),2,"reopened history survives save and navigation")
	_finish()
