extends "res://tests/display_ui.gd"

func _run() -> void:
	OS.add_logger(captured)
	var args: PackedStringArray=OS.get_cmdline_user_args()
	if args.size()==2 and args[0]=="--output": output=args[1]
	DirAccess.make_dir_recursive_absolute(output); display_report={"captures":[]}
	var watchdog: Timer=Timer.new(); watchdog.wait_time=90; watchdog.one_shot=true; watchdog.timeout.connect(func() -> void: t.expect(false,"start menu timeout"); _finish()); root.add_child(watchdog); watchdog.start()
	await set_resolution(Vector2i(2560,1440))
	app=(load("res://scenes/main.tscn") as PackedScene).instantiate() as Control; root.add_child(app); await _frames()
	t.expect(_button("ContinueSurvivalTissuesButton")==null,"no disabled Continue on fresh menu")
	t.equal(_button("NewSurvivalTissuesButton").text,"Новое воплощение","fresh primary caption")
	t.equal(app.find_children("*","Button",true,false).size(),4,"exactly two primary and two corner buttons")
	t.expect(app.find_child("OtherModesOverlay",true,false)==null,"examples do not clutter normal menu")
	for dimensions: Vector2i in [Vector2i(2560,1440),Vector2i(1920,1080),Vector2i(1280,720),Vector2i(1280,800)]:
		await set_resolution(dimensions)
		var close_rect: Rect2=_button("QuitButton").get_global_rect(); var settings_rect: Rect2=_button("SettingsButton").get_global_rect()
		t.equal(close_rect.size,settings_rect.size,"corner controls have identical size")
		t.expect(settings_rect.end.x<close_rect.position.x,"settings sits left of close")
		t.expect(_button("CampaignsButton").get_global_rect().end.x<_button("NewSurvivalTissuesButton").global_position.x,"slot icon sits left of primary")
		await _capture("new-%s-%s.png" % [dimensions.x,dimensions.y])
	await _press("SettingsButton")
	t.expect(app.find_child("SettingsScreen",true,false)!=null,"corner settings opens working screen")
	await _press("SettingsBack")
	await _press("CampaignsButton")
	t.expect(_button("QuitButton").disabled and _button("SettingsButton").disabled,"modal blocks background controls and keyboard focus")
	t.equal(app.find_children("CampaignOpen_*","Button",true,false).size(),3,"chooser exposes exactly three slots")
	await _press("CampaignSelect_1"); await _key(KEY_ESCAPE)
	t.equal(app._page,"menu","closing chooser never starts a world")
	await _press("NewSurvivalTissuesButton")
	life=app.find_child("LifeScreen",true,false) as Sm2LifeScreen
	var second: Sm2JourneySession=life.session as Sm2JourneySession
	t.equal((second._store as Sm2CampaignStore).campaign_index,1,"new incarnation starts selected empty slot")
	t.expect(not app._campaigns().occupied(1),"new game does not silently save")
	await _press("WorldSave"); var saved: String=second.state_hash()
	var path: String=second._store._slot_path(second.slot_name()); var bytes: PackedByteArray=FileAccess.get_file_as_bytes(path)
	await _press("PsiTrain"); var unsaved: String=second.state_hash()
	await _press("WorldMenu")
	t.equal(_button("ContinueSurvivalTissuesButton").text,"Продолжить","saved primary has exact caption")
	t.expect(_button("NewSurvivalTissuesButton")==null,"saved primary replaces new-game button")
	t.expect((app.find_child("MenuSaveHint",true,false) as Label).text.contains("UTC"),"save metadata labels its timezone")
	await set_resolution(Vector2i(2560,1440)); await _capture("continue-2560.png")
	await _press("ResumeMainButton")
	t.expect(app._life==second and second.state_hash()==unsaved,"chooser return retains unsaved current object")
	t.equal(FileAccess.get_file_as_bytes(path),bytes,"return never writes save")
	await _press("WorldMenu"); await _press("ContinueSurvivalTissuesButton")
	t.equal(app._life.state_hash(),saved,"Continue loads disk rather than live unsaved state")
	# A later save wins even after selecting an older slot in the chooser.
	await create_timer(1.1).timeout
	await _press("WorldMenu"); await _press("CampaignsButton"); await _press("CampaignOpen_0")
	await _press("Travel_ruins"); await _press("WorldSave")
	var newest: String=app._life.state_hash()
	await _press("WorldMenu"); await _press("CampaignsButton"); await _press("CampaignSelect_1"); await _press("CampaignClose")
	await _press("ContinueSurvivalTissuesButton")
	t.equal((app._life._store as Sm2CampaignStore).campaign_index,0,"Continue ignores selected older slot")
	t.equal(app._life.state_hash(),newest,"Continue restores latest world exactly")
	# Active battles restore at the same turn; opening the menu never advances them.
	await _press("WorldBattle"); screen=app.find_child("BattleScreen",true,false) as Sm2BattleScreen; screen.auto_advance=false
	await _press("SaveBattleButton"); var in_battle: String=app._life.state_hash()
	await _press("BattleMenuButton"); await _press("WorldMenu"); await _press("ContinueSurvivalTissuesButton")
	t.equal(app._life.state_hash(),in_battle,"continuation of active battle does not advance simulation")
	await _press("WorldMenu")
	# Invalid primary with a valid backup remains recoverable from the compact menu.
	var first_path: String=app._life._store._slot_path(app._life.slot_name())
	var file: FileAccess=FileAccess.open(first_path,FileAccess.WRITE); file.store_string("{broken"); file.close()
	app._redraw_page(); await _frames()
	await _press("ContinueSurvivalTissuesButton")
	t.expect((app._life._store as Sm2CampaignStore).recovered,"Continue restores valid backup")
	t.expect((app.find_child("CampNotice",true,false) as Label).text.contains("резервная копия"),"recovery is explained")
	await _press("WorldMenu")
	for slot: int in [0,1]:
		var bad_path: String=app._campaigns().store(slot)._slot_path("survival_tissues")
		for suffix: String in ["",".bak"]:
			file=FileAccess.open(bad_path+suffix,FileAccess.WRITE); file.store_string("{unavailable"); file.close()
	app._redraw_page(); await _frames()
	t.expect(_button("NewSurvivalTissuesButton")==null,"damaged saves are not treated as absence")
	var live: Sm2LifeSession=app._life; var live_hash: String=live.state_hash()
	await _press("ContinueSurvivalTissuesButton")
	t.expect(app.find_child("CampaignChooser",true,false)!=null,"unavailable Continue opens slot explanations")
	t.expect(app._life==live and live.state_hash()==live_hash,"failed continuation preserves existing live world")
	await _capture("damaged-slots.png")
	await _key(KEY_ESCAPE)
	# A cold start must still discover occupied slots without inventing a live game.
	root.remove_child(app); app.queue_free(); await _frames()
	app=(load("res://scenes/main.tscn") as PackedScene).instantiate() as Control; root.add_child(app); await _frames()
	t.expect(app._life==null,"restart has no fabricated live session")
	t.expect(_button("ContinueSurvivalTissuesButton")!=null,"restart discovers occupied slots")
	_finish()
